import pytest


@pytest.fixture
def ddd_json():
    return {
        "state": "MA",
        "cities": [
            "VILA NOVA DOS MARTÍRIOS",
            "TUNTUM",
            "TRIZIDELA DO VALE",
            "TIMON",
            "TIMBIRAS",
            "TASSO FRAGOSO",
            "SUCUPIRA DO RIACHÃO",
            "SUCUPIRA DO NORTE",
            "SÍTIO NOVO",
            "SENADOR LA ROCQUE",
            "SENADOR ALEXANDRE COSTA",
            "SÃO ROBERTO",
            "SÃO RAIMUNDO DO DOCA BEZERRA",
            "SÃO RAIMUNDO DAS MANGABEIRAS",
            "SÃO PEDRO DOS CRENTES",
            "SÃO PEDRO DA ÁGUA BRANCA",
            "SÃO MATEUS DO MARANHÃO",
            "SÃO LUÍS GONZAGA DO MARANHÃO",
            "SÃO JOSÉ DOS BASÍLIOS",
            "SÃO JOÃO DOS PATOS",
            "SÃO JOÃO DO SOTER",
            "SÃO JOÃO DO PARAÍSO",
            "SÃO FRANCISCO DO MARANHÃO",
            "SÃO FRANCISCO DO BREJÃO",
            "SÃO FÉLIX DE BALSAS",
            "SÃO DOMINGOS DO MARANHÃO",
            "SÃO DOMINGOS DO AZEITÃO",
            "SANTO ANTÔNIO DOS LOPES",
            "SANTA FILOMENA DO MARANHÃO",
            "SAMBAÍBA",
            "RIBAMAR FIQUENE",
            "RIACHÃO",
            "PRESIDENTE DUTRA",
            "PORTO FRANCO",
            "POÇÃO DE PEDRAS",
            "PERITORÓ",
            "PEDREIRAS",
            "PASTOS BONS",
            "PASSAGEM FRANCA",
            "PARNARAMA",
            "PARAIBANO",
            "NOVA IORQUE",
            "NOVA COLINAS",
            "MONTES ALTOS",
            "MIRADOR",
            "MATÕES",
            "LORETO",
            "LIMA CAMPOS",
            "LAJEADO NOVO",
            "LAGOA GRANDE DO MARANHÃO",
            "LAGO DOS RODRIGUES",
            "LAGOA DO MATO",
            "LAGO VERDE",
            "LAGO DO JUNCO",
            "LAGO DA PEDRA",
            "JOSELÂNDIA",
            "JOÃO LISBOA",
            "JENIPAPO DOS VIEIRAS",
            "JATOBÁ",
            "ITINGA DO MARANHÃO",
            "ITAIPAVA DO GRAJAÚ",
            "IMPERATRIZ",
            "IGARAPÉ GRANDE",
            "GRAJAÚ",
            "GRAÇA ARANHA",
            "GOVERNADOR LUIZ ROCHA",
            "GOVERNADOR EUGÊNIO BARROS",
            "GOVERNADOR EDISON LOBÃO",
            "GOVERNADOR ARCHER",
            "GONÇALVES DIAS",
            "FORTUNA",
            "FORTALEZA DOS NOGUEIRAS",
            "FORMOSA DA SERRA NEGRA",
            "FERNANDO FALCÃO",
            "FEIRA NOVA DO MARANHÃO",
            "ESTREITO",
            "ESPERANTINÓPOLIS",
            "DOM PEDRO",
            "DAVINÓPOLIS",
            "COROATÁ",
            "COLINAS",
            "CODÓ",
            "CIDELÂNDIA",
            "CAXIAS",
            "CAROLINA",
            "CAPINZAL DO NORTE",
            "CAMPESTRE DO MARANHÃO",
            "BURITIRANA",
            "BURITI BRAVO",
            "BOM LUGAR",
            "BERNARDO DO MEARIM",
            "BENEDITO LEITE",
            "BARRA DO CORDA",
            "BARÃO DE GRAJAÚ",
            "BALSAS",
            "BACABAL",
            "ARAME",
            "AMARANTE DO MARANHÃO",
            "ALTO PARNAÍBA",
            "ALTO ALEGRE DO MARANHÃO",
            "ALDEIAS ALTAS",
            "AÇAILÂNDIA",
        ],
    }
